### ISSUE TITLE
Change the name of the Hiero website repository to something more specific

### ISSUE THREAD

**Issue by Ndacyayisenga-droid** [hiero-ledger/hiero-website#12]
I would like to suggest changing the name of the Hiero website repository to something more specific, such as `hiero-website`. The current repository name, `website` , is quite common and may lead to confusion for users who fork the repo, as many will likely have similarly named repositories in their GitHub accounts.
<img width="718" alt="Screenshot 1403-07-18 at 04 49 48" src="https://github.com/user-attachments/assets/92bdc06b-3cd3-411c-9297-2a4fac336b19">

**Comment by hendrikebbers** [comment]
Good point! We should use `hiero-website`. @ryjones what is the best workflow to have all in sync with CoWarden?

**Comment by ryjones** [comment]
1: [comment this out](https://github.com/LFDT-Hiero/governance/blob/cdf941cd4fa6ff9185d56ec90000b586c4948d77/config.yaml#L56-L60)
2: after it is applied, rename the repo
3: after renaming, edit block above to reflect new name

**Comment by hendrikebbers** [comment]
@ryjones I'm not allowed to rename the repo. Can you take care of it and rename it to `hiero-website`?

**Comment by hendrikebbers** [comment]
THX

**Comment by hendrikebbers** [comment]
repo renamed
